### ISSUE TITLE
Update SWF Object 

### ISSUE THREAD

**Issue by NicolasSiver** [syranide/react-swf#7]
Hi.

So if I want to refresh `ReactSWF`, I should provide new `key` property?
Because changing of FlashVars doesn't do anything ;)

Something like this:

```as3
render: function () {
            var key = keyIndex++;
            return (
                <div className="player">
                    <ReactSWF
                        key={key}
                        src={this.props.swfUrl}
                        id="hdsPlayer"
                        width={this.state.componentWidth}
                        height={this.state.componentHeight}
                        wmode="transparent"
                        flashVars={this.props.flashVars}/>
                </div>
            );
        }
```

**Comment by syranide** [comment]
Correct.

Changes to FlashVars (and most other properties) after creation is not reflected by the running SWF. I decided that treating the component as stateful rather than automatically reset it made the most sense, so yeah it needs to be keyed accordingly (unless you want to update the dynamically via `ExternalInterface`). Also, FYI this extends to `src` as well, so changing the filename won't automatically load the new SWF either.

PS. Although thinking about it, having an explicit `reset`-method could be handy for certain use-cases too, I'll probably make that available in next release. I should probably document all this too, thanks! :)

**Comment by syranide** [comment]
Closing this, feel free to reopen if you have any follow-up questions.
