### ISSUE TITLE
Call function from Flash

### ISSUE THREAD

**Issue by AssafHason** [syranide/react-swf#9]
I want call javascript function from Flash.
I use ExternalInterface in flash action as:

ExternalInterface.call("buttonClicked", buttonNumber);

but where should I put the function buttonClicked in the react and how it get the variable ButtonNumber in react?

Please explain and give us any simple example.
it will be very helpful.

many thanks

**Comment by syranide** [comment]
ReactSWF has no possibility of providing any useful *unopinionated* abstraction, so you have to do it the same way it's always done. Expose a globally accessible JavaScript function and provide its name through flashVars or w/e to the SWF so that it knows which function to call. So as this is nothing specific to ReactSWF I'd recommend reading up on how to use ExternalInterface in general and building on that.

**Comment by AssafHason** [comment]
Thanks, while the ExternalInterface example show that we should put on JS func inside the head tag, we wish to put them inside our React code, thus not in the same scope and not accessible.

Any idea how to access funcs that are defined inside the React code, for example inside a render func?

**Comment by syranide** [comment]
You can't, it has to be a globally accessible function, either with a unique per-swf function name or a shared function with a per-swf identifying argument.

**Comment by syranide** [comment]
FYI https://github.com/syranide/react-swf/issues/12#issuecomment-146793158
